### ISSUE TITLE
Change `go install` instructions in README

### ISSUE THREAD

**Issue by aashutoshrathi** [plutov/ultrafocus#12]
## Description

Since `'go install' requires a version when the current directory is not in a module`.
The following should be changed
https://github.com/plutov/ultrafocus/blob/ffca7968cda19a54651627f22494bd3ecc48ee10/README.md?plain=1#L20-L22

to 
```bash 
go install github.com/plutov/ultrafocus@latest
```

**Comment by plutov** [comment]
@aashutoshrathi looks good!
