### ISSUE TITLE
v0.1.5 freezed when enter blacklist 

### ISSUE THREAD

**Issue by Kunniii** [plutov/ultrafocus#3]
When i select `> blacklist` the app freeze for a few seconds (3 to 10 secs). After that, it shows the list of domains with the last entry ending with a color code.

![image](https://github.com/user-attachments/assets/e9740b4c-ceb4-4c93-bcc9-4dbaf849a9f2)

**Comment by plutov** [comment]
@Kunniii have you or anyone you know worked with bubbletea? This bug kills me, sometimes it works as expected, sometimes it freezes...

**Comment by plutov** [comment]
@Kunniii btw what terminal are you using ?

**Comment by Kunniii** [comment]
It's Alacritty

**Comment by plutov** [comment]
I am using oh-my-zsh and warp.dev

**Comment by plutov** [comment]
This issue is strange, sometimes it works, sometimes it hangs.

**Comment by plutov** [comment]
<img width="391" alt="Screenshot 2024-07-24 at 20 33 36" src="https://github.com/user-attachments/assets/cdedf4d7-f7f7-4cc7-8993-4884cef96ac6">
I end up with these weird symbols in input. Not sure where they come from.

**Comment by Kunniii** [comment]
I think the problem is when we load the hosts to show it on `textarea`. Once you write the hosts to the `hosts` file, the next time it loads correctly.

**Comment by plutov** [comment]
When I comment this line it work well, but we kind of need to set the value there.
```
// m.textarea.SetValue(strings.Join(m.domains, "\n"))
```

**Comment by plutov** [comment]
@Kunniii I solved it by overriding the styles of textarea. I noticed that this issue is caused by libgloss.Adaptive and doesn't appear if I use constant colors. Please install the latest version and verify.

**Comment by Kunniii** [comment]
Great! I also noticed that the color code is from the default LibGloss style of the textare! Thanks for the fix!
