### ISSUE TITLE
consider looking at StevenBlack/hosts project

### ISSUE THREAD

**Issue by ccoVeille** [plutov/ultrafocus#5]
I'm unsure if you know this wonderful project

https://github.com/StevenBlack/hosts

Your project made me think about it.

Maybe you could take a look at it.

StevenBlack/hosts is published with MIT License, so you can copy and paste anything you want. It's OK

Maybe your project is inspired from StevenBlack/hosts, then you could mention it in the README

**Comment by plutov** [comment]
Thanks a lot, I actually didn't know about this project but it looks really cool. I may use some ideas from there, for example much more sophisticated list of domains is cool.
