### ISSUE TITLE
Redirect to a Focus Page

### ISSUE THREAD

**Issue by newtoallofthis123** [plutov/ultrafocus#7]
Since `ultrafocus` blocks websites by binding them to `127.0.0.1` / loop back address, it would be interesting if it can run a small webserver on a go routine or some mechanism such as spawning to redirect blocked websites to a simple focus page

**Comment by plutov** [comment]
Good idea! I was thinking the same. Either to have a nice page on 127.0.0.1 or redirect to some public IP address with a nice focus message.

**Comment by plutov** [comment]
I added running a server ins the background which returns a random motivational message.
One TODO: serve TLS on :443

**Comment by plutov** [comment]
Done!
